export const invoices = [
  {
    id: "INV-001",
    customer: "Ahmed Al Mansouri",
    date: new Date(2024, 4, 1),
    amount: 1250,
    status: "paid",
    items: [
      { name: "Premium Kandura", quantity: 1, price: 850 },
      { name: "Embroidery Service", quantity: 1, price: 400 },
    ],
    paymentMethod: "Cash",
  },
  {
    id: "INV-002",
    customer: "Fatima Mohammed",
    date: new Date(2024, 4, 2),
    amount: 850,
    status: "paid",
    items: [
      { name: "Premium Abaya", quantity: 1, price: 750 },
      { name: "Alteration Service", quantity: 1, price: 100 },
    ],
    paymentMethod: "Card",
  },
  {
    id: "INV-003",
    customer: "Khalid Rahman",
    date: new Date(2024, 4, 3),
    amount: 450,
    status: "pending",
    items: [{ name: "Standard Kandura", quantity: 1, price: 450 }],
    paymentMethod: "Pending",
  },
  {
    id: "INV-004",
    customer: "Sara Al Ameri",
    date: new Date(2024, 4, 5),
    amount: 1650,
    status: "paid",
    items: [
      { name: "Premium Abaya", quantity: 1, price: 750 },
      { name: "Premium Kandura", quantity: 1, price: 850 },
      { name: "Alteration Service", quantity: 1, price: 50 },
    ],
    paymentMethod: "Card",
  },
  {
    id: "INV-005",
    customer: "Mohammed Ali",
    date: new Date(2024, 4, 7),
    amount: 950,
    status: "overdue",
    items: [
      { name: "Premium Kandura", quantity: 1, price: 850 },
      { name: "Alteration Service", quantity: 1, price: 100 },
    ],
    paymentMethod: "Pending",
  },
  {
    id: "INV-006",
    customer: "Layla Khan",
    date: new Date(2024, 4, 8),
    amount: 1150,
    status: "paid",
    items: [
      { name: "Premium Abaya", quantity: 1, price: 750 },
      { name: "Scarf (Silk)", quantity: 2, price: 200 },
    ],
    paymentMethod: "Mobile",
  },
  {
    id: "INV-007",
    customer: "Hassan Al Farsi",
    date: new Date(2024, 4, 10),
    amount: 2250,
    status: "paid",
    items: [
      { name: "Premium Kandura", quantity: 2, price: 1700 },
      { name: "Embroidery Service", quantity: 2, price: 550 },
    ],
    paymentMethod: "Card",
  },
  {
    id: "INV-008",
    customer: "Aisha Mahmood",
    date: new Date(2024, 4, 12),
    amount: 750,
    status: "pending",
    items: [{ name: "Premium Abaya", quantity: 1, price: 750 }],
    paymentMethod: "Pending",
  },
]
